/**
 * Стили роликов: всё в одном-двух цветах, цветной только акцент (ключевое слово, рамка, мелочь).
 * История в каждом ролике нарисована в своём, контрастном стиле — как гравюры у образца.
 */
import type { Theme } from './engine.ts';

const MONT = "'Montserrat', sans-serif";
const SERIF = "'Liberation Serif', 'DejaVu Serif', serif";
const MONO = "'Liberation Mono', 'DejaVu Sans Mono', monospace";
const glow = (c: string) => `drop-shadow(0 0 3px ${c}) drop-shadow(0 0 14px ${c.replace(/[\d.]+\)$/, '0.35)')})`;
const GRAIN_D = 'url(grain-dark.png)';
const GRAIN_L = 'url(grain-light.png)';

/** Старая бумага с тёмной печатью — для истории в нескольких роликах. */
const oldPaper = (labelFont = MONT) => ({
  bg: '#e6e1d6',
  ink: '#1d1b18',
  fill: '#e6e1d6',
  accent: '#1d1b18',
  dark: false,
  stroke: 5,
  overlay: `${GRAIN_D}, radial-gradient(75% 60% at 50% 45%, rgba(0,0,0,0) 55%, rgba(0,0,0,0.45) 100%)`,
  font: MONT,
  labelBg: '#1d1b18',
  labelInk: '#efebe3',
  labelBorder: '#efebe3',
  labelFont,
});

export const THEMES: Record<string, Theme> = {
  /** 1. Мел на школьной доске. */
  chalk: {
    bg: '#2c2f2e',
    ink: '#efeee8',
    fill: '#2c2f2e',
    accent: '#f4d35e',
    dark: true,
    stroke: 6,
    lineFilter: 'blur(0.35px)',
    overlay: 'url(chalk.png)',
    font: MONT,
    cap: 'plain',
    hist: oldPaper(),
  },
  /** 2. Тушь на белой бумаге; история — светлым по тёмному, как старый негатив. */
  ink: {
    bg: '#f5f3ee',
    ink: '#151515',
    fill: '#f5f3ee',
    accent: '#d62828',
    dark: false,
    stroke: 6,
    overlay: GRAIN_D,
    overlayBlend: 'multiply',
    font: MONT,
    cap: 'plain',
    hist: {
      bg: '#161514',
      ink: '#ebe6db',
      fill: '#161514',
      accent: '#d62828',
      dark: true,
      stroke: 5,
      overlay: `${GRAIN_L}, radial-gradient(75% 60% at 50% 45%, rgba(0,0,0,0) 55%, rgba(0,0,0,0.6) 100%)`,
      font: MONT,
      labelBg: '#ebe6db',
      labelInk: '#161514',
      labelBorder: '#161514',
      labelFont: SERIF,
    },
  },
  /** 3. Светящиеся линии на чёрном (как у образца); история — «греческая ваза»: терракота на чёрном. */
  glow: {
    bg: '#000',
    ink: '#fff',
    fill: '#000',
    accent: '#ff7a1a',
    dark: true,
    stroke: 6,
    lineFilter: glow('rgba(255,255,255,0.85)'),
    spot: 'radial-gradient(45% 30% at 50% 50%, rgba(140,140,150,0.28), rgba(0,0,0,0) 80%)',
    font: MONT,
    cap: 'plain',
    hist: {
      bg: '#120e0c',
      ink: '#d9773a',
      fill: '#120e0c',
      accent: '#d9773a',
      dark: true,
      stroke: 6,
      overlay: `${GRAIN_L}, radial-gradient(75% 60% at 50% 45%, rgba(0,0,0,0) 55%, rgba(0,0,0,0.6) 100%)`,
      font: MONT,
      labelBg: '#120e0c',
      labelInk: '#d9773a',
      labelBorder: '#d9773a',
      labelFont: SERIF,
    },
  },
  /** 4. Карандаш в тетради в клетку; синий — только ручка-акцент. */
  pencil: {
    bg: `repeating-linear-gradient(0deg, transparent 0 39px, #d9dde3 39px 41px), repeating-linear-gradient(90deg, transparent 0 39px, #d9dde3 39px 41px), #f8f7f3`,
    ink: '#383838',
    fill: '#f8f7f3',
    accent: '#2a5bd7',
    dark: false,
    stroke: 4.5,
    overlay: GRAIN_D,
    overlayBlend: 'multiply',
    font: MONT,
    cap: 'type',
    hist: oldPaper(SERIF),
  },
  /** 5. Чертёж: светлые линии на графите с сеткой. */
  blueprint: {
    bg: `repeating-linear-gradient(0deg, transparent 0 59px, rgba(255,255,255,0.07) 59px 61px), repeating-linear-gradient(90deg, transparent 0 59px, rgba(255,255,255,0.07) 59px 61px), #1c2024`,
    ink: '#e8edf2',
    fill: '#1c2024',
    accent: '#ff4b4b',
    dark: true,
    stroke: 5,
    font: MONT,
    cap: 'plain',
    hist: {
      bg: '#0e1012',
      ink: '#c9d1d9',
      fill: '#0e1012',
      accent: '#ff4b4b',
      dark: true,
      stroke: 5,
      overlay: `${GRAIN_L}, repeating-linear-gradient(0deg, rgba(255,255,255,0.04) 0 2px, transparent 2px 6px)`,
      font: MONT,
      labelBg: '#0e1012',
      labelInk: '#e8edf2',
      labelBorder: '#ff4b4b',
      labelFont: MONO,
    },
  },
  /** 6. Комикс: жирная тушь, растр, подписи в рамках. */
  comic: {
    bg: '#fbf8f0',
    ink: '#111',
    fill: '#fff',
    accent: '#ffcc00',
    dark: false,
    stroke: 7,
    overlay: 'radial-gradient(circle, rgba(0,0,0,0.13) 1.6px, transparent 2px) 0 0 / 12px 12px',
    font: MONT,
    cap: 'box',
    hist: {
      bg: '#111',
      ink: '#fbf8f0',
      fill: '#111',
      accent: '#ffcc00',
      dark: true,
      stroke: 6,
      overlay: 'radial-gradient(circle, rgba(255,255,255,0.12) 1.6px, transparent 2px) 0 0 / 12px 12px',
      font: MONT,
      labelBg: '#ffcc00',
      labelInk: '#111',
      labelBorder: '#111',
      labelFont: MONT,
    },
  },
  /** 7. Вырезанная бумага с тенью и печатная машинка. */
  paper: {
    bg: '#cfc8b8',
    ink: '#1b1b1b',
    fill: '#f3efe6',
    accent: '#f26a1b',
    dark: false,
    stroke: 4.5,
    lineFilter: 'drop-shadow(7px 9px 0 rgba(0,0,0,0.2))',
    overlay: GRAIN_D,
    overlayBlend: 'multiply',
    font: MONO,
    cap: 'type',
    capSize: 40,
    hist: { ...oldPaper(MONO), bg: '#f3efe6', fill: '#f3efe6' },
  },
  /** 8. Ночной город: белые линии, жёлтое такси. */
  night: {
    bg: 'linear-gradient(#04060b, #0b0f18)',
    ink: '#fff',
    fill: '#06080d',
    accent: '#ffc93c',
    dark: true,
    stroke: 6,
    lineFilter: glow('rgba(255,255,255,0.8)'),
    spot: 'radial-gradient(40% 25% at 50% 58%, rgba(255,201,60,0.12), rgba(0,0,0,0) 80%)',
    font: MONT,
    cap: 'plain',
    hist: {
      bg: '#2b2d30',
      ink: '#dcdcdc',
      fill: '#2b2d30',
      accent: '#ffc93c',
      dark: true,
      stroke: 5,
      overlay: `${GRAIN_L}, radial-gradient(80% 60% at 50% 40%, rgba(255,255,255,0.08), rgba(0,0,0,0.5) 100%)`,
      font: MONT,
      labelBg: '#111',
      labelInk: '#ffc93c',
      labelBorder: '#ffc93c',
      labelFont: SERIF,
    },
  },
  /** 9. Газета: чёрная печать на серой бумаге, заголовки с засечками. */
  news: {
    bg: '#e8e3d6',
    ink: '#1a1a1a',
    fill: '#e8e3d6',
    accent: '#c1121f',
    dark: false,
    stroke: 5,
    overlay: GRAIN_D,
    overlayBlend: 'multiply',
    font: SERIF,
    cap: 'tag',
    capSize: 44,
    hist: { ...oldPaper(SERIF), bg: '#d3cdbe', fill: '#d3cdbe' },
  },
  /** 10. Ночь в спальне: лунный свет. */
  moon: {
    bg: 'linear-gradient(#0a0d18, #141a31)',
    ink: '#dfe6ff',
    fill: '#0b0e1a',
    accent: '#a594ff',
    dark: true,
    stroke: 6,
    lineFilter: glow('rgba(200,210,255,0.7)'),
    spot: 'radial-gradient(35% 25% at 70% 30%, rgba(200,210,255,0.16), rgba(0,0,0,0) 80%)',
    font: MONT,
    cap: 'plain',
    hist: {
      bg: '#e7e8ee',
      ink: '#20243a',
      fill: '#e7e8ee',
      accent: '#a594ff',
      dark: false,
      stroke: 5,
      overlay: `${GRAIN_D}, radial-gradient(75% 60% at 50% 45%, rgba(0,0,0,0) 55%, rgba(0,0,30,0.4) 100%)`,
      font: MONT,
      labelBg: '#20243a',
      labelInk: '#e7e8ee',
      labelBorder: '#a594ff',
      labelFont: SERIF,
    },
  },
};
